all:
  children:
    linux:
      hosts:
        mon01:
          ansible_host: 10.10.20.20
          ansible_connection: local
        client01:
          ansible_host: 10.10.30.100
      vars:
        ansible_user: thomas
    windows:
      hosts:
        dc01:
          ansible_host: 10.10.20.10
      vars:
        ansible_user: Administrator
        ansible_password: "{{ vault_dc_admin_password }}"
        ansible_connection: winrm
        ansible_winrm_transport: basic
        ansible_winrm_server_cert_validation: ignore
        ansible_port: 5985
